trigger:
  branches:
    include:
    - main
  paths:
    include:
    - terraform-azurerm-vnet-main/terraform-azurerm-vnet-main
stages:
- stage: Validate
  displayName: Validate
  jobs:
  - job: validate
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
  # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ConnectedServiceName: $(ARMConnection)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azurerm-vnet-main/terraform-azurerm-vnet-main'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(container_name) -backend-config=key=$(key)'
        backendType: 'selfConfigured'
  # Validate
    - task: TerraformCLI@0
      displayName: Validate Config
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azurerm-vnet-main/terraform-azurerm-vnet-main'
    
- stage: Plan
  displayName: Plan
  jobs:
  - job: plan
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
  # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ConnectedServiceName: $(ARMConnection)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azurerm-vnet-main/terraform-azurerm-vnet-main'
        commandOptions: '-upgrade -backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(container_name) -backend-config=key=$(key)'
        backendType: 'selfConfigured'
  # Plan
    - task: TerraformCLI@0
      displayName: Plan Terraform Deployment
      env:
        AZcon: $(sas_token)
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azurerm-vnet-main/terraform-azurerm-vnet-main'
# Approve
- stage: Approve
  displayName: Approve
  jobs:
  - job: approve
    displayName: Wait for approval
    pool: server
    steps: 
    - task: ManualValidation@0
      timeoutInMinutes: 60
      inputs:
        notifyUsers: 'johnjcairns99@yahoo.co.uk'
        instructions: 'Review the plan in the next hour'
- stage: Apply
  displayName: Apply
  jobs:
  - job: apply
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
  # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ConnectedServiceName: $(ARMConnection)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azurerm-vnet-main/terraform-azurerm-vnet-main'
        commandOptions: '-upgrade -backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(container_name) -backend-config=key=$(key)'
        backendType: 'selfConfigured'
  # Apply
    - task: TerraformCLI@0
      displayName: Apply Terraform Deployment
      env:
        ConnectedServiceName: $(ARMConnection)
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azurerm-vnet-main/terraform-azurerm-vnet-main'
        commandOptions: '-auto-approve'